---
title: "Preparcial"
author: "Andres David Gomez B"
date: "25 de febrero de 2018"
output:
  html_document:
    df_print: 
  #pdf_document: default
  #word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Horner
## 2. Numeros binarios
```{r}
rm(list=ls())
# convierte los numeros decimales en binario
binario <- function(a) {
  x<-floor(a)
  d<-a-x
  #Variables del programa
  e<-0
  y<-0
  i<-1
  #parte entera
  while(2<=x)
  {
    y<-x%%2
    x<-floor(x/2)
    if(y==0)
    {
      e[c(i)]<-0
      i<-i+1
    }
    else
    {
      e[c(i)]<-1
      i<-i+1
    }
  }
  if(x==0)
  {
    e[c(i)]<-0
  }
  else
  {
    e[c(i)]<-1
  }
  while(0<i)
  {
    cat(e[c(i)])
    i<-i-1
  }
  cat(".")
  #parte decimal
  i<-1
  e<-0
  y<-d
  while(i<=15)
  {
    y<-y*2
    d<-floor(y)
    if(d==0)
    {
      e[c(i)]<-0
      i<-i+1
    }
    else
    {
      e[c(i)]<-1
      i<-i+1
    }
    y<-y-d
  }
  x<-1
  while(x<=i-1)
  {
    cat(e[c(x)])
    x<-x+1
  }
}
binario(3.1416)
#11,001001000011111
```
Ahora a la inversa
```{r}
rm(list=ls())
# convierte los numeros binarios a decimales
decimal <- function(a,b) {
tam<-length(a)
#Parte entera
j<-0
sum<-0
res<-0
while(0<tam)
{
  res<-((a[c(tam)]))
  if(res!=0)
  {
    sum=sum+(res*2^j) 
  }
  tam<-tam-1
  j<-j+1
}
#cat(sum,".")
#parte decimal
tam<-length(b)
j<-1
while((j<=tam))
{
  res<-(b[c(j)])
  if(res!=0)
  {
    sum=sum+(res*2^((j)*(-1))) 
  }
  j<-j+1
}
cat(sum)
}
a<-c(1,1,1)
b<-c(1,1,1,1,1,1)
decimal(a,b)

```

##3.Binarios infinitos

1. ¿ Como se ajusta un numero binario infinito en un numero finito de bits?
2. ¿Cual es la diferencia entre redondeo y recorte?
4. Idique el numero de punto flotante (IEEE) de precision doble asociado a x, el cual se denota como fl(x); para x(0.4).


